apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: api-connect-instance
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apiconnect-small
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-GVEN-GFUPVE
    metric: VIRTUAL_PROCESSOR_CORE
    use: production
  management:
    testAndMonitor:
      enabled: true
      autoTestEnabled: true
      aiEnabled: false
  endpointTypes:
    - Events
    - APIs
  analytics:
    storage:
      enabled: true
      type: shared
  profile: n3xc14.m48
  version: 10.0.5.2-ifix1-124
  storageClassName: ocs-storagecluster-ceph-rbd
  allowUpgrade: true

