apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
  name: namespaces
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: cp4i
    server: https://kubernetes.default.svc
  project: cp4i
  source:
    repoURL: https://github.com/cz-integration/cp4i-gitops.git
    path: namespaces/resources
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
